twig:
    default_path: '%kernel.project_dir%/templates'
    # Importation du module Bootstrap pour les formulaires :
    form_themes: ['bootstrap_5_layout.html.twig']
when@test:
    twig:
        strict_variables: true
